import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "TTC-admin",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>Sign in as a super admin</div>
  )
}

export default page